### ISSUE TITLE
Security Policy Required to launch

### ISSUE THREAD

**Issue by bipruitt** [ebob9/cg-syslog-apigw#6]
If there is not a Security Policy present in the tenant, the script will error out upon 

launch./Users/billpruitt/Documents/Screenshots/Screen Shot 2019-01-10 at 9.15.25 AM.png

Once a security policy is created the script will successfully initialize.

**Comment by ebob9** [comment]
@bipruitt can you post the screenshot again? It came in as just a text line to the file..

**Comment by bipruitt** [comment]
<img width="1085" alt="screen shot 2019-01-10 at 9 15 25 am" src="https://user-images.githubusercontent.com/13052573/51003692-ca9fc980-1505-11e9-9555-bba063aefbf5.png">

**Comment by ebob9** [comment]
This is actually a bug in the cloudgenix_idname script, fixing that will fix it here.

**Comment by ebob9** [comment]
Fixed in cloudgenix_idname by https://github.com/ebob9/cloudgenix-idname/commit/7bae95b13fe80f9e25a1476e222abd0916cb25af
